### ISSUE TITLE
URLs with Parameters are Borken

### ISSUE THREAD

**Issue by imartin22k** [Necarri/The-Cooler-UnevenBotcat654#7]
Jeremiah said so, here is the fix if the url is a string:
"&".join(split(url, "&")[0:1])

**Comment by tootizard** [comment]
Simpler:
CleanerUrl=url.split('&')[0]

**Comment by Necarri** [comment]
Implemented in latest release

**Comment by imartin22k** [comment]
Ahh I did have my syntax wrong, I realize now that the watch parameter had a "?" not a "&" so you would only need the first value of that list. Whoops lol
